# Generated by Django 2.2.26 on 2023-03-19 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user_profile_images')),
                ('user_description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.TextField(blank=True, null=True)),
                ('pet_type', models.TextField(blank=True, null=True)),
                ('pet_age', models.TextField(blank=True, null=True)),
                ('pet_description', models.TextField(blank=True, null=True)),
                ('pet_picture', models.ImageField(upload_to='pet_images')),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PetItOutApp.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petprofileBlue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petprofileBlue', to='PetItOutApp.PetProfile')),
                ('petprofileRed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petprofileRed', to='PetItOutApp.PetProfile')),
            ],
        ),
    ]
