# Generated by Django 2.2.26 on 2023-03-18 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PetItOutApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petprofileBlue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petprofileBlue', to='PetItOutApp.PetProfile')),
                ('petprofileRed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petprofileRed', to='PetItOutApp.PetProfile')),
            ],
        ),
    ]
