# Generated by Django 2.2.26 on 2023-03-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetItOutApp', '0002_auto_20230316_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editprofile',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='petprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
