# Generated by Django 2.2.26 on 2023-03-16 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PetItOutApp', '0003_auto_20230316_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='editprofile',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PetItOutApp.UserProfile'),
            preserve_default=False,
        ),
    ]
